# Generated by Django 4.1.4 on 2023-05-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note_materie_student',
            name='nota',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=100),
            preserve_default=False,
        ),
    ]
