# Generated by Django 4.1.4 on 2023-05-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_note_materie_student_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='an_studiu',
            options={'verbose_name_plural': 'An Studiu'},
        ),
        migrations.AlterModelOptions(
            name='date_personale',
            options={'verbose_name_plural': 'Date Personale'},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name_plural': 'Mail'},
        ),
        migrations.AlterModelOptions(
            name='materiile_grupelor',
            options={'verbose_name_plural': 'Materiile Grupelor'},
        ),
        migrations.AlterModelOptions(
            name='note_materie_student',
            options={'verbose_name_plural': 'Note Materii Student'},
        ),
        migrations.AlterField(
            model_name='date_personale',
            name='an_studiu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.an_studiu'),
        ),
        migrations.AlterField(
            model_name='date_personale',
            name='semestru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.semestru'),
        ),
        migrations.AlterField(
            model_name='materiile_profesorului',
            name='CNP_profesor',
            field=models.ForeignKey(limit_choices_to={'CNP__is_active': True, 'CNP__is_staff': True, 'CNP__is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to='hr.date_personale'),
        ),
        migrations.AlterField(
            model_name='note_materie_student',
            name='Date_Personale',
            field=models.ForeignKey(limit_choices_to={'CNP__is_active': True, 'CNP__is_staff': False, 'CNP__is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to='hr.date_personale'),
        ),
    ]
