# Generated by Django 4.1.4 on 2023-05-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_an_studiu_options_alter_date_personale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_personale',
            name='an_studiu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.an_studiu'),
        ),
        migrations.AlterField(
            model_name='date_personale',
            name='semestru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.semestru'),
        ),
    ]
