# Generated by Django 4.1.4 on 2023-05-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_date_personale_an_studiu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_personale',
            name='an_studiu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.an_studiu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='date_personale',
            name='semestru',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.semestru'),
            preserve_default=False,
        ),
    ]
