# Generated by Django 4.1.4 on 2023-05-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_date_personale_an_studiu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noutati',
            name='link',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
