# Generated by Django 4.1.4 on 2023-05-06 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0007_alter_date_personale_cnp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_personale',
            name='adresa_mail',
        ),
        migrations.AddField(
            model_name='date_personale',
            name='grupa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.grupa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupa',
            name='link',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='date_personale',
            name='CNP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
