# Generated by Django 4.1.4 on 2023-05-07 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_date_personale_adresa_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_personale',
            old_name='CNP',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='materiile_profesorului',
            old_name='CNP_profesor',
            new_name='Date_Profesor',
        ),
        migrations.RenameField(
            model_name='materiile_profesorului',
            old_name='materie',
            new_name='Materie',
        ),
        migrations.RenameField(
            model_name='note_materie_student',
            old_name='Date_Personale',
            new_name='Date_Student',
        ),
        migrations.RenameField(
            model_name='noutati',
            old_name='adresa_mail',
            new_name='Date_Personale',
        ),
        migrations.RemoveField(
            model_name='date_personale',
            name='an_studiu',
        ),
        migrations.RemoveField(
            model_name='date_personale',
            name='grupa',
        ),
        migrations.RemoveField(
            model_name='date_personale',
            name='semestru',
        ),
        migrations.CreateModel(
            name='Grupa_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=200)),
                ('An_Studiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.an_studiu')),
                ('Date_Student', models.ForeignKey(limit_choices_to={'CNP__is_active': True, 'CNP__is_staff': False, 'CNP__is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to='hr.date_personale')),
                ('Grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.grupa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
