# Generated by Django 4.1.4 on 2023-05-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_rename_cnp_date_personale_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupa_student',
            options={'verbose_name_plural': 'Grupele Studentilor'},
        ),
        migrations.AlterModelTable(
            name='grupa_student',
            table='grupa_student',
        ),
    ]
