# Generated by Django 4.1.4 on 2023-05-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_grupa_student_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='an_studiu',
            old_name='file_backup',
            new_name='an',
        ),
        migrations.RenameField(
            model_name='grupa',
            old_name='file_backup',
            new_name='an',
        ),
        migrations.RemoveField(
            model_name='materiile_profesorului',
            name='titlu',
        ),
        migrations.AlterField(
            model_name='grupa_student',
            name='Date_Student',
            field=models.ForeignKey(limit_choices_to={'User__is_active': True, 'User__is_staff': False, 'User__is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to='hr.date_personale'),
        ),
        migrations.AlterField(
            model_name='materiile_profesorului',
            name='Date_Profesor',
            field=models.ForeignKey(limit_choices_to={'User__is_active': True, 'User__is_staff': True, 'User__is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to='hr.date_personale'),
        ),
        migrations.AlterField(
            model_name='note_materie_student',
            name='Date_Student',
            field=models.ForeignKey(limit_choices_to={'User__is_active': True, 'User__is_staff': False, 'User__is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, to='hr.date_personale'),
        ),
    ]
